<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    private function getCategoryData()
    {
        return [
            'basic' => [
                'title' => 'Basic',
                'description' => 'Essential text case conversion tools for everyday text formatting needs.',
                'color' => 'blue',
                'icon' => '<svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>',
                'tools' => [
                    ['name' => 'Alternate Case', 'description' => 'Alternate between upper and lowercase', 'url' => '/basic/alternate-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4"/></svg>'],
                    ['name' => 'Capitalize Words', 'description' => 'Capitalize first letter of each word', 'url' => '/basic/capitalize-words', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/></svg>'],
                    ['name' => 'Invert Case', 'description' => 'Invert uppercase to lowercase and vice versa', 'url' => '/basic/invert-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Lower Case', 'description' => 'Convert text to lowercase letters', 'url' => '/basic/lower-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8V4m0 0L13 8m4-4l4 4"/></svg>'],
                    ['name' => 'Sentence Case', 'description' => 'Capitalize first letter of sentences', 'url' => '/basic/sentence-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536"/></svg>'],
                    ['name' => 'Strikethrough', 'description' => 'Add strikethrough effect to text', 'url' => '/basic/strikethrough', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Title Case', 'description' => 'Convert text to title case formatting', 'url' => '/basic/title-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6"/></svg>'],
                    ['name' => 'Underline', 'description' => 'Add underline formatting to text', 'url' => '/basic/underline', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4"/></svg>'],
                    ['name' => 'Upper Case', 'description' => 'Convert text to uppercase letters', 'url' => '/basic/upper-case', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4"/></svg>']
                ]
            ],
            'counter' => [
                'title' => 'Counter',
                'description' => 'Analyze and count various elements in your text.',
                'color' => 'green',
                'icon' => '<svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2z"/></svg>',
                'tools' => [
                    ['name' => 'Character and Word Counter', 'description' => 'Count characters, words, and paragraphs', 'url' => '/counter/character-word-counter', 'icon' => '<svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5"/></svg>'],
                    ['name' => 'Count Each Line', 'description' => 'Count characters or words per line', 'url' => '/counter/count-each-line', 'icon' => '<svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/></svg>'],
                    ['name' => 'Bracket and Tag Counter', 'description' => 'Count brackets and tags in text', 'url' => '/counter/bracket-tag-counter', 'icon' => '<svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>']
                ]
            ],
            'formatter' => [
                'title' => 'Formatter',
                'description' => 'Beautify and format your code with proper indentation.',
                'color' => 'purple',
                'icon' => '<svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>',
                'tools' => [
                    ['name' => 'CSS Beautifier', 'description' => 'Format and beautify CSS code', 'url' => '/formatter/css-beautifier', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414"/></svg>'],
                    ['name' => 'HTML Beautifier', 'description' => 'Format and beautify HTML code', 'url' => '/formatter/html-beautifier', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>'],
                    ['name' => 'JavaScript Beautifier', 'description' => 'Format and beautify JavaScript code', 'url' => '/formatter/javascript-beautifier', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l3 3-3 3m5 0h3"/></svg>'],
                    ['name' => 'JSON Beautifier', 'description' => 'Format and beautify JSON data', 'url' => '/formatter/json-beautifier', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6"/></svg>'],
                    ['name' => 'SQL Beautifier', 'description' => 'Format and beautify SQL queries', 'url' => '/formatter/sql-beautifier', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7"/></svg>']
                ]
            ],
            'modify' => [
                'title' => 'Modify',
                'description' => 'Modify and transform your text in various ways.',
                'color' => 'indigo',
                'icon' => '<svg class="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536"/></svg>',
                'tools' => [
                    ['name' => 'Add Number To Each Line', 'description' => 'Add numbers to each line', 'url' => '/modify/add-number-to-each-line', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/></svg>'],
                    ['name' => 'Add String After Number of Characters', 'description' => 'Add text after specific character count', 'url' => '/modify/add-string-after-characters', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>'],
                    ['name' => 'Add Text To Each Line', 'description' => 'Add prefix or suffix to each line', 'url' => '/modify/add-text-to-each-line', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>'],
                    ['name' => 'Column to Comma', 'description' => 'Convert columns to comma-separated', 'url' => '/modify/column-to-comma', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>'],
                    ['name' => 'Commas Between Numbers', 'description' => 'Add commas as thousand separators', 'url' => '/modify/commas-between-numbers', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Comma to Column', 'description' => 'Convert comma-separated to columns', 'url' => '/modify/comma-to-column', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>'],
                    ['name' => 'Convert Double Space To Single Space', 'description' => 'Convert double spaces to single', 'url' => '/modify/double-space-to-single', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Convert Single Space To Double Space', 'description' => 'Convert single spaces to double', 'url' => '/modify/single-space-to-double', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Keep First Characters Of Each Line', 'description' => 'Keep only first N characters per line', 'url' => '/modify/keep-first-characters', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>'],
                    ['name' => 'Keep Last Characters Of Each Line', 'description' => 'Keep only last N characters per line', 'url' => '/modify/keep-last-characters', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>'],
                    ['name' => 'Keep Lines Containing A Certain Word', 'description' => 'Keep lines with specific word', 'url' => '/modify/keep-lines-with-word', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>'],
                    ['name' => 'Keep Lines Containing A Certain Words', 'description' => 'Keep lines with any of specified words', 'url' => '/modify/keep-lines-with-words', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>'],
                    ['name' => 'Merge Text or Lists', 'description' => 'Merge multiple text lists together', 'url' => '/modify/merge-text-lists', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"/></svg>'],
                    ['name' => 'Number To Words', 'description' => 'Convert numbers to written words', 'url' => '/modify/number-to-words', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Prefix Suffix', 'description' => 'Add prefix and suffix to text', 'url' => '/modify/prefix-suffix', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>'],
                    ['name' => 'Specified Position Text Addition', 'description' => 'Add text at specific position', 'url' => '/modify/position-text-addition', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>'],
                    ['name' => 'Trim Text', 'description' => 'Remove whitespace from beginning and end', 'url' => '/modify/trim-text', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>']
                ]
            ],
            'special-effects' => [
                'title' => 'Special Effects',
                'description' => 'Apply special text effects and styling.',
                'color' => 'pink',
                'icon' => '<svg class="w-6 h-6 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>',
                'tools' => [
                    ['name' => 'Backward', 'description' => 'Reverse text character by character', 'url' => '/special-effects/backward', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Binary Code To Text', 'description' => 'Convert binary code to readable text', 'url' => '/special-effects/binary-to-text', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16"/></svg>'],
                    ['name' => 'Bold', 'description' => 'Make text bold and emphasized', 'url' => '/special-effects/bold', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 4h8a4 4 0 014 4 4 4 0 01-4 4H6z"/></svg>'],
                    ['name' => 'Bold Gothic Text', 'description' => 'Convert to bold gothic style text', 'url' => '/special-effects/bold-gothic', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 4h8a4 4 0 014 4"/></svg>'],
                    ['name' => 'Bold Italic', 'description' => 'Make text both bold and italic', 'url' => '/special-effects/bold-italic', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 4l4 16"/></svg>'],
                    ['name' => 'Circled Text', 'description' => 'Put characters in circles', 'url' => '/special-effects/circled', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z"/></svg>'],
                    ['name' => 'Cursive Bold', 'description' => 'Convert to cursive bold style', 'url' => '/special-effects/cursive-bold', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 4l4 16"/></svg>'],
                    ['name' => 'Flip Text', 'description' => 'Flip text upside down', 'url' => '/special-effects/flip-text', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4"/></svg>'],
                    ['name' => 'Flip Words', 'description' => 'Flip the order of words', 'url' => '/special-effects/flip-words', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Gothic Text', 'description' => 'Convert to gothic style text', 'url' => '/special-effects/gothic', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01"/></svg>'],
                    ['name' => 'Italic', 'description' => 'Make text italic and slanted', 'url' => '/special-effects/italic', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 4l4 16"/></svg>'],
                    ['name' => 'Outline Text', 'description' => 'Create outlined text effect', 'url' => '/special-effects/outline', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z"/></svg>'],
                    ['name' => 'Parentheses Around Letters', 'description' => 'Put parentheses around each character', 'url' => '/special-effects/parentheses', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>'],
                    ['name' => 'Pascal Case', 'description' => 'Convert to PascalCase format', 'url' => '/special-effects/pascal-case', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/></svg>'],
                    ['name' => 'Reverse Words', 'description' => 'Reverse the order of words', 'url' => '/special-effects/reverse-words', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Slashed', 'description' => 'Add slashes through text', 'url' => '/special-effects/slashed', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Snake Case', 'description' => 'Convert to snake_case format', 'url' => '/special-effects/snake-case', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>'],
                    ['name' => 'Upside Down Text', 'description' => 'Flip text upside down', 'url' => '/special-effects/upside-down', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4"/></svg>'],
                    ['name' => 'Wide Text', 'description' => 'Make text wider with spacing', 'url' => '/special-effects/wide-text', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>']
                ]
            ],
            'extract' => [
                'title' => 'Extract',
                'description' => 'Extract specific data from your text.',
                'color' => 'yellow',
                'icon' => '<svg class="w-6 h-6 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10"/></svg>',
                'tools' => [
                    ['name' => 'Extract Emails', 'description' => 'Extract email addresses from text', 'url' => '/extract/emails', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Extract Hex Colors', 'description' => 'Extract hexadecimal color codes from text', 'url' => '/extract/hex-colors', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4z"/></svg>'],
                    ['name' => 'Extract Image Urls', 'description' => 'Extract image URLs from text', 'url' => '/extract/image-urls', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Extract IP Address', 'description' => 'Extract IP addresses from text', 'url' => '/extract/ip-address', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"/></svg>'],
                    ['name' => 'Extract Phone Numbers', 'description' => 'Extract phone numbers from text', 'url' => '/extract/phone-numbers', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/></svg>'],
                    ['name' => 'Extract Numbers From Text', 'description' => 'Extract all numbers from text', 'url' => '/extract/numbers', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"/></svg>'],
                    ['name' => 'Extract Text Between', 'description' => 'Extract text between specific characters', 'url' => '/extract/text-between', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6"/></svg>'],
                    ['name' => 'Extract Urls', 'description' => 'Extract web URLs from text', 'url' => '/extract/urls', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>'],
                    ['name' => 'Extract Random Lines', 'description' => 'Extract random lines from text', 'url' => '/extract/random-lines', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4l11.733 16h4.267l-11.733-16z"/></svg>'],
                    ['name' => 'Extract Zip Codes', 'description' => 'Extract postal/zip codes from text', 'url' => '/extract/zip-codes', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/></svg>']
                ]
            ],
            'sorting' => [
                'title' => 'Sorting',
                'description' => 'Sort and arrange your text in different ways.',
                'color' => 'teal',
                'icon' => '<svg class="w-6 h-6 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4h13M3 8h9m-9 4h9m5-4v12m0 0l-4-4m4 4l4-4"/></svg>',
                'tools' => [
                    ['name' => 'Alphabetical Sort', 'description' => 'Sort lines alphabetically A-Z or Z-A', 'url' => '/sorting/alphabetical', 'icon' => '<svg class="w-4 h-4 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4h13M3 8h9m-9 4h6"/></svg>'],
                    ['name' => 'Length Sort', 'description' => 'Sort lines by character length', 'url' => '/sorting/length', 'icon' => '<svg class="w-4 h-4 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4h13M3 8h9m-9 4h9"/></svg>'],
                    ['name' => 'Randomly Sort Lines of Text', 'description' => 'Randomly shuffle lines of text', 'url' => '/sorting/random', 'icon' => '<svg class="w-4 h-4 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4l11.733 16h4.267l-11.733-16z"/></svg>'],
                    ['name' => 'Sort Numbers', 'description' => 'Sort numbers in ascending or descending order', 'url' => '/sorting/numbers', 'icon' => '<svg class="w-4 h-4 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>']
                ]
            ],
            'remove' => [
                'title' => 'Remove',
                'description' => 'Remove specific content from your text.',
                'color' => 'red',
                'icon' => '<svg class="w-6 h-6 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>',
                'tools' => [
                    ['name' => 'Remove Consonants', 'description' => 'Remove all consonant letters from text', 'url' => '/remove/consonants', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Duplicate Lines', 'description' => 'Remove duplicate lines from text', 'url' => '/remove/duplicate-lines', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>'],
                    ['name' => 'Remove Duplicate Words', 'description' => 'Remove duplicate words from text', 'url' => '/remove/duplicate-words', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>'],
                    ['name' => 'Remove Empty Lines', 'description' => 'Remove blank or empty lines', 'url' => '/remove/empty-lines', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 18h7"/></svg>'],
                    ['name' => 'Remove Extra Spaces', 'description' => 'Remove extra spaces between words', 'url' => '/remove/extra-spaces', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove First Characters', 'description' => 'Remove first N characters from each line', 'url' => '/remove/first-characters', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>'],
                    ['name' => 'Remove HTML Comments', 'description' => 'Remove HTML comments from code', 'url' => '/remove/html-comments', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>'],
                    ['name' => 'Remove HTML Tags', 'description' => 'Remove HTML tags and keep only text', 'url' => '/remove/html-tags', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>'],
                    ['name' => 'Remove Last Characters', 'description' => 'Remove last N characters from each line', 'url' => '/remove/last-characters', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>'],
                    ['name' => 'Remove Letters', 'description' => 'Remove all letters and keep only numbers/symbols', 'url' => '/remove/letters', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Line Breaks', 'description' => 'Remove line breaks and join text', 'url' => '/remove/line-breaks', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>'],
                    ['name' => 'Remove Lines With Word', 'description' => 'Remove lines containing specific words', 'url' => '/remove/lines-with-word', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Numbers', 'description' => 'Remove all numbers from text', 'url' => '/remove/numbers', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Remove Numbers From Text', 'description' => 'Remove numeric characters from text', 'url' => '/remove/numbers-from-text', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Remove Quotes', 'description' => 'Remove quotation marks from text', 'url' => '/remove/quotes', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Single Quotes', 'description' => 'Remove single quotation marks', 'url' => '/remove/single-quotes', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Spaces', 'description' => 'Remove all spaces from text', 'url' => '/remove/spaces', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Special Characters', 'description' => 'Remove special characters and symbols', 'url' => '/remove/special-characters', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Specific Words', 'description' => 'Remove specific words from text', 'url' => '/remove/specific-words', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Tabs', 'description' => 'Remove tab characters from text', 'url' => '/remove/tabs', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove Text Between', 'description' => 'Remove text between specific delimiters', 'url' => '/remove/text-between', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Remove URLs', 'description' => 'Remove web URLs from text', 'url' => '/remove/urls', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>'],
                    ['name' => 'Remove Vowels', 'description' => 'Remove vowel letters from text', 'url' => '/remove/vowels', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>'],
                    ['name' => 'Trim Spaces', 'description' => 'Remove leading and trailing spaces', 'url' => '/remove/trim-spaces', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>']
                ]
            ],
            'replace' => [
                'title' => 'Replace',
                'description' => 'Find and replace text with new content.',
                'color' => 'orange',
                'icon' => '<svg class="w-6 h-6 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"/></svg>',
                'tools' => [
                    ['name' => 'Replace New Line with Commas', 'description' => 'Replace line breaks with commas', 'url' => '/replace/newline-with-commas', 'icon' => '<svg class="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>'],
                    ['name' => 'Replace Spaces', 'description' => 'Replace spaces with other characters', 'url' => '/replace/spaces', 'icon' => '<svg class="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Replace Text Between', 'description' => 'Replace text between delimiters', 'url' => '/replace/text-between', 'icon' => '<svg class="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
                    ['name' => 'Search And Replace', 'description' => 'Find and replace text with new text', 'url' => '/replace/search-replace', 'icon' => '<svg class="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>']
                ]
            ],
            'conversions' => [
                'title' => 'Conversions',
                'description' => 'Convert between different text formats and encodings.',
                'color' => 'cyan',
                'icon' => '<svg class="w-6 h-6 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"/></svg>',
                'tools' => [
                    ['name' => 'Base64 Decoder', 'description' => 'Decode Base64 encoded text', 'url' => '/conversions/base64-decoder', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Base64 Encoder', 'description' => 'Encode text to Base64 format', 'url' => '/conversions/base64-encoder', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Date Conversion', 'description' => 'Convert between different date formats', 'url' => '/conversions/date', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Decimal to String', 'description' => 'Convert decimal numbers to text', 'url' => '/conversions/decimal-to-string', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Html Entities Converter', 'description' => 'Convert HTML entities to characters', 'url' => '/conversions/html-entities', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>'],
                    ['name' => 'String to Decimal', 'description' => 'Convert text to decimal numbers', 'url' => '/conversions/string-to-decimal', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Text To Binary Code', 'description' => 'Convert text to binary code', 'url' => '/conversions/text-to-binary', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16"/></svg>'],
                    ['name' => 'Url Decode', 'description' => 'Decode URL-encoded text', 'url' => '/conversions/url-decode', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>'],
                    ['name' => 'Url Encode', 'description' => 'Encode text for URL usage', 'url' => '/conversions/url-encode', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>']
                ]
            ],
            'generators' => [
                'title' => 'Generators',
                'description' => 'Generate random data and content.',
                'color' => 'emerald',
                'icon' => '<svg class="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>',
                'tools' => [
                    ['name' => 'Lorem Ipsum Generator', 'description' => 'Generate Lorem Ipsum placeholder text', 'url' => '/generators/lorem-ipsum', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>'],
                    ['name' => 'Random Phone Number Generator', 'description' => 'Generate random phone numbers', 'url' => '/generators/random-phone-number', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/></svg>'],
                    ['name' => 'Random Color Generator', 'description' => 'Generate random colors and codes', 'url' => '/generators/color', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4z"/></svg>'],
                    ['name' => 'Random Date Generator', 'description' => 'Generate random dates', 'url' => '/generators/date', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Random Email Generator', 'description' => 'Generate random email addresses', 'url' => '/generators/email', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Random IP address Generator', 'description' => 'Generate random IP addresses', 'url' => '/generators/ip', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"/></svg>'],
                    ['name' => 'Random ipv6 Address Generator', 'description' => 'Generate random IPv6 addresses', 'url' => '/generators/ipv6', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"/></svg>'],
                    ['name' => 'Random MAC address Generator', 'description' => 'Generate random MAC addresses', 'url' => '/generators/mac', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"/></svg>'],
                    ['name' => 'Random Number Generator', 'description' => 'Generate random numbers', 'url' => '/generators/number', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'Random User-agent Generator', 'description' => 'Generate random user agent strings', 'url' => '/generators/user-agent', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>'],
                    ['name' => 'Random Password Generator', 'description' => 'Generate secure random passwords', 'url' => '/generators/password', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"/></svg>'],
                    ['name' => 'SEO Friendly URL Generator', 'description' => 'Generate SEO-friendly URLs', 'url' => '/generators/seo-url', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>'],
                    ['name' => 'Sequential Number Generator', 'description' => 'Generate sequential numbers', 'url' => '/generators/sequential-number', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16"/></svg>'],
                    ['name' => 'URL Slug Generator', 'description' => 'Generate URL slugs from text', 'url' => '/generators/url-slug', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101"/></svg>']
                ]
            ],
            'studio' => [
                'title' => '✨ Studio',
                'description' => 'Advanced text processing and workflow tools.',
                'color' => 'violet',
                'icon' => '<svg class="w-6 h-6 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>',
                'tools' => [
                    ['name' => 'TextFlow Pipeline', 'description' => 'Advanced text processing pipeline', 'url' => '/studio/text-flow', 'icon' => '<svg class="w-4 h-4 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>']
                ]
            ]
        ];
    }

    private function getRelatedCategories()
    {
        return [
            ['name' => 'Basic', 'slug' => 'basic', 'count' => 9, 'color' => 'blue', 'icon' => '<svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01"/></svg>'],
            ['name' => 'Counter', 'slug' => 'counter', 'count' => 3, 'color' => 'green', 'icon' => '<svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5"/></svg>'],
            ['name' => 'Formatter', 'slug' => 'formatter', 'count' => 5, 'color' => 'purple', 'icon' => '<svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16"/></svg>'],
            ['name' => 'Modify', 'slug' => 'modify', 'count' => 17, 'color' => 'indigo', 'icon' => '<svg class="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536"/></svg>'],
            ['name' => 'Special Effects', 'slug' => 'special-effects', 'count' => 19, 'color' => 'pink', 'icon' => '<svg class="w-4 h-4 text-pink-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>'],
            ['name' => 'Extract', 'slug' => 'extract', 'count' => 10, 'color' => 'yellow', 'icon' => '<svg class="w-4 h-4 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10"/></svg>'],
            ['name' => 'Sorting', 'slug' => 'sorting', 'count' => 4, 'color' => 'teal', 'icon' => '<svg class="w-4 h-4 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4h13M3 8h9m-9 4h9"/></svg>'],
            ['name' => 'Remove', 'slug' => 'remove', 'count' => 23, 'color' => 'red', 'icon' => '<svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7"/></svg>'],
            ['name' => 'Replace', 'slug' => 'replace', 'count' => 4, 'color' => 'orange', 'icon' => '<svg class="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4"/></svg>'],
            ['name' => 'Conversions', 'slug' => 'conversions', 'count' => 9, 'color' => 'cyan', 'icon' => '<svg class="w-4 h-4 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"/></svg>'],
            ['name' => 'Generators', 'slug' => 'generators', 'count' => 14, 'color' => 'emerald', 'icon' => '<svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>'],
            ['name' => '✨ Studio', 'slug' => 'studio', 'count' => 1, 'color' => 'violet', 'icon' => '<svg class="w-4 h-4 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>']
        ];
    }

    public function show($category)
    {
        $categories = $this->getCategoryData();
        $relatedCategories = $this->getRelatedCategories();
        
        if (!isset($categories[$category])) {
            abort(404);
        }
        
        $categoryData = $categories[$category];
        
        // Filter out current category from related categories
        $relatedCategories = array_filter($relatedCategories, function($cat) use ($category) {
            return $cat['slug'] !== $category;
        });
        
        return view('category', compact('categoryData', 'relatedCategories'));
    }
}